version: "3.9"

services:
  server:
    build: ./server
    command: bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - ./server:/shadowsin
    ports:
      - "${SERVER_PORT}:3000"
      # Debug Ports:
      - "1234:1234"
      - "26162:26162"
    depends_on:
      - db
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
