require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
