export enum ActiveSkillName {
  astral = 'Astral',
  athletics = 'Athletics',
  biotech = 'Biotech',
  closeCombat = 'Close Combat',
  con = 'Con',
  conjuring = 'Conjuring',
  cracking = 'Cracking',
  electronics = 'Electronics',
  enchanting = 'Enchanting',
  engineering = 'Engineering',
  exoticWeapons = 'Exotic Weapons',
  firearms = 'Firearms',
  influence = 'Influence',
  outdoors = 'Outdoors',
  perception = 'Perception',
  piloting = 'Piloting',
  sorcery = 'Sorcery',
  stealth = 'Stealth',
  tasking = 'Tasking',
}
