name: Deploy
on: [ push ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock

      - name: Configure
        run: |
          echo "REACT_APP_ENABLE_SERVER=false" > .env
          echo "REACT_APP_SERVER_URL=http://ShadowSIN.app" > .env

      - name: Install
        working-directory: ./client
        run: "yarn install"

      - name: Build
        working-directory: ./client
        run: "yarn build"

      - name: Deploy
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -u "github-actions-bot <support+actions@github.com>"
